### ISSUE TITLE
reaction

### ISSUE THREAD

**Issue by Kimtav** [littlestudios69/Little_Music#14]
bug form reaction (  if u request song ready . u send any message and u reaction any emoji auto remove reaction with message ) 
i thiank error form remove all reaction

**Comment by taynotfound** [comment]
Hello Kimtav,

Could you please provide the Error that comes in the Console, A bit of Context and a better sentence?

~ Tayron

**Comment by taynotfound** [comment]
Hello Kimtav,

Just a reminder that we still need to get more Infos. See message above.

Please respond in 2 days else this Issue will be closed.

~ Tayron

**Comment by taynotfound** [comment]
Closed due to inactivity

~ Tayron
