### ISSUE TITLE
Credits? 

### ISSUE THREAD

**Issue by Tomato6966** [littlestudios69/Little_Music#15]
I am the creator so Credit me pls

**Comment by taynotfound** [comment]
![Screenshot_20210713_120351](https://user-images.githubusercontent.com/50525948/125433446-d6da7d06-5606-4e96-918f-55da3f118225.jpg)
Here we have a Disclaimer that is even put on the Table of Contents, On the Bot's Help, Stats and other Commands

~Tayron, CEO of Little Studios

**Comment by taynotfound** [comment]
Closed due to no need of having that open.

Do not lock the Convo

~ Tayron, CEO of Little Studios

**Comment by Tomato6966** [comment]
thanks

**Comment by taynotfound** [comment]
Np. Next Time please look at the code before asking for sth that is already there.

Will lock this in 2 hours.

~ Tayron - CEO of Little Studios

**Comment by Tomato6966** [comment]
I looked but found nothing

**Comment by Tomato6966** [comment]
I was on phone tho
