### ISSUE TITLE
m!radio list randomly stops working

### ISSUE THREAD

**Issue by ImFelixprogram** [littlestudios69/Little_Music#3]
The page switcher sometimes randomly stops working after a short period of time without any error or message. If somebody, that has done more on this project than I have, could look into it that would be nice, because that would make finding the error easier than me having to look through the whole code - if noone does, I would do that tomorrow.

**Comment by taynotfound** [comment]
I think this is the normal timeout

**Comment by ImFelixprogram** [comment]
I highly doubt that because the timeout is 45 seconds and it did not work way before that.

**Comment by taynotfound** [comment]
works fine for me tbh. Just let this issue open maybe some users have this too

**Comment by ImFelixprogram** [comment]
I was not able to get to the last page unless I go back a page (which brings me to the last page if I'm on page 1), I'll wait if someone finds why that is, if not, I'll do tomorrow, as I said

**Comment by taynotfound** [comment]
kk. Worked for me. We will see

**Comment by ImFelixprogram** [comment]
@tayron1 I found the issue, and replaced the collector timeout with a timeout that counts for how long nothing happened with the reactions only instead of couting even if pages are being swapped regularly. Also a message will tell the user that the time has ran out and will delete the reactions now.
Commit fixing that is [667a0201d0854823f34774d9f884edfee62c9cd5](https://github.com/littlestudios69/Little_Music/commit/667a0201d0854823f34774d9f884edfee62c9cd5)

~ Felixprogram, CTO of Little Studios
