### ISSUE TITLE
Feature Request: Stage Radio 24/7

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Little_Music#4]
Please add the Feature that the Bot is 24/7 in Stage Channel and starts Playing an specifc Radio on Join

**Comment by rexjohannes** [comment]
![Like this](http://rexum.rf.gd/ZUrbj34hN0o.png)

**Comment by rexjohannes** [comment]
Like this Like this: http://rexum.rf.gd/ZUrbj34hN0o.png from Groovy

**Comment by ImFelixprogram** [comment]
(Issue has the same content as https://github.com/littlestudios69/Pika/issues/12 , all further conversation will take place there for both projects)

**Comment by taynotfound** [comment]
Hello Johannes,


We already have a 24/7 Function but we will look into the Stage Support!


Tayron

**Comment by taynotfound** [comment]
After quite some time we finally intigrated it!


Thank you for your Suggestion!
