### ISSUE TITLE
Canary Version

### ISSUE THREAD

**Issue by ghost** [littlestudios69/Little_Music#5]
Could there be a canary version, which is just a "less stable" version of the main bot? This would have all the same features, just a second version that would have beta features, etc on it.

**Comment by taynotfound** [comment]
Hello Joshua,


We will look into this Request! I can't promise anything tho cuz it would suck some more Ressources.

Tayron

**Comment by taynotfound** [comment]
Forgot to Say sth but we now have multiple versions for the Bot in this Server: https://discord.gg/dUENj5A3TS
