### ISSUE TITLE
Feature: Radio Search

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Little_Music#7]
Please add an Function to Search for an Radio Station and get the ID because the RadioList is very long

**Comment by taynotfound** [comment]
Heya Johannes,


This is a good Enhancement! We will try to implement that!

_btw you can always try to make the stuff urself to help us_

**Comment by taynotfound** [comment]
Hello Johannes,

I'm currently not seeing a way on how to implement this.

If you have an Idea please leave it below! I will close this issue but **not** lock it so you can provide me with some ideas on how to implement this!

Your Tayron ~ CEO of Little Studios
