### ISSUE TITLE
Feature: LautFM Command

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Little_Music#8]
m!laut tac-fm

an command that plays an laut fm station by name

https://stream.laut.fm/rexradio
https://stream.laut.fm/tac-fm

https://stream.laut.fm/{station}

**Comment by taynotfound** [comment]
Hello Johannes,

That is a cool feature idea. We will implement that in the Next Update ^^

**Comment by taynotfound** [comment]
**Hello Johannes**

We decided to add your Idea into the Bot!

It is now in our Development Code and will be released with all the other Changes comming soon!

[![LM_LAUT_FM_CMD_SHOWCASE](https://cdn.tixte.com/uploads/tayron.steals-code.tk/kpzbmmqlh9a.png)](https://youtu.be/ydOClfEQ2Zo)

Your Tayron ~ CEO of Little Studios
